# .streamlit/secrets.toml

# API keys (ensure not to commit and share keys in public repositories)
KEY_OPENAI = "..."

KEY_ANTHROPIC = "..."

KEY_GOOGLE = "AIzaSyAzQhL3385Mf46Il29gDffeqQy2hYFNZOw"

DROPBOX_APP_KEY = "rdlfqzaxbmuy5gi"
DROPBOX_APP_SECRET = "ppmbbr9msqnap9i"
#auth = "WNrRTLbrBO8AAAAAAAAupg3hG0BemBNXezys6S8aBoA"
DROPBOX_REFRESH_TOKEN = "Xyhq5FA_rgsAAAAAAAAAAVaHQe61IxKhPCYXo6FVM-6wJB9RcR8ArmGLzKKmS-Y7"

#DROPBOX_ACCESS_TOKEN = "sl.u.AGVeBKoZ9VUqwTE7c3bes-nXDzTHD14iBEaLnbMRBhv6FatfIzGKqzjov_EEOxVB5NTyG6E0VDvC3Od_CHEVJVRSQoRiQqmqUnWYVeMrhtuvAd-by5Gep8iWXxbyydhoHi1KO3tCjrfWv-i8Q3Od0B0NrIbMVhZWLdfO2RqubkXqMp1uNUqbErIEZGGxDUUtzHdKogorQBzYCqarQFUuA_vNTdQZ5g_BNEpNCQ97V_WsiN3H4wiFO6z2ShftWcvS9hnxw0dhARdD4-XMkDOTkkDox9eIc5VycfUSyu5fEJO6T0aD5Tp09MfVMkFagGSPalcF9f-coJBetxxnV7gZ9611UIAZKY9Gnv4U0tWM9-_tPL8u5Da1KVSnLdU8b1xUi_Q_ENpamvXIyBAgajdgvLDDBm5sRzCP04PjLuZGatjaCnbtiGReqsAa6SuQFEjBxWmHuzfsiBCUk6gh2eMOsVMqKCDeb-kNqSVrMrZ1p3Lg4F4VjShDhFOgMWatJpY9-IJ1OdB_ctFpZzUfcya-Cd-JwrVhfaq8N1adctft_PgTBSua19bZH9XNLjETXxjZf_b24vBXFcoe2kDCJiIfVKylnh0zR1NgaJvfszivGiryoCnDVYkaAfdbUBV2d6zcHIhZ5DBZCgnjd9Hqq9ULGgN5j6a7-GIu4kODPKy00zG-HNNL3HThV4qH0_2kSxkcfVBRvxMesgccMLri69lkmjBRToFOH4E_LpCMqWx6eGecOHQzLLYYXLEGFe-2HfILKXSIOLF6MGULLyTwoA3mb7_YTQTqxzxa6KJrPqzGoO72GWbENrma7YGWHn1WDDgLc26akFAFN9ySZImf8LqM_iswrJaUCnr-5xDZjr296e74w8npGiOvSllh2nw4B353nHdI0LvNZjufdBIUR5t04AS1IXgUKVe5TU_tzTnC4VM0cRm7yWegy1oz4ur6GQVB_onNXt7jS2JD64hrSMVH2bSgXAj8oXJy-z5z0hjeIpaXAx_NxaSozlsAaJshBoU4gUqkejnf9cWlmTgtUmajMWKdCrmHbx2BqxyC7-TEjvKs8y6NiKHdBP7hKSfx20kCdiFoZHLpoHd59QrINetPP3S-OqWYL5VI99oBW8TeB7Ki8DpnaMiXT4Gk9BbYvevuzFUPVFYsOsV5pDZ_EvV-Z-Y8yLRpOm-hFth0mTFHzpu5XgwI_-AJQYjw0fExogJdVNENDQgU5IINljoHSCXT2Wu8RwlCsXoCrxKgX8IEDmeEnbI9rDNVGqKjr8us26bJKsduRecHvQl5F0Da6rsAspSNu9_1Buybak_FCup6mPCPhw"
ENDPOINT_AZURE = "..."
VERSION_AZURE = "..."
KEY_AZURE = "..."

# Section for account names and passwords (ensure to change these before your study)
[passwords]

# Test account (can attempt interview multiple times)
testaccount = "testpw"

# Accounts (have to be alphanumeric; each account can complete the interview once)
95u9kr3rm3 = "mr4cl168dq"
8x19twme52 = "fwi5l5q7hy"
d2gvynxrs5 = "3z43x8rg89"
4k3j1ucz56 = "5gm1z6m121"
# Further accounts in the format 'accountname = "password"' can be added here
# Always make sure to anonymise account names and passwords appropriately
